
# Board settings.
#BOARD = atmega328
#BOARD = pro5v328

MON_SPEED = 9600

# Where to find header files and libraries.
LIB_DIRS = ../../ /local/arduino-100/libraries/Wire/ /local/arduino-100/libraries/Wire/utility/

include ../../../Makefile.master

