
# Board settings.
#BOARD = atmega328

# Where to find header files and libraries.
LIB_DIRS = ../../ /usr/share/arduino-0022/libraries/Wire/ /usr/share/arduino-0022/libraries/Wire/utility/

include ../../../Makefile.master

